DROP TABLE ACCOUNT;
CREATE TABLE ACCOUNT(
    USER_NO NUMBER PRIMARY KEY,
    USER_ID VARCHAR2(30) NOT NULL UNIQUE,
    USER_PWD VARCHAR2(30) NOT NULL,
    USER_NNAME VARCHAR2(20) NOT NULL UNIQUE
);
CREATE SEQUENCE SEQ_USERNO;