--1.
CREATE TABLE TB_CATEGORY(
    NAME VARCHAR2(10),
    USE_YN CHAR(1) DEFAULT 'Y'
);

--2.
CREATE TABLE TB_CLASS_TYPE(
    NO VARCHAR2(5) PRIMARY KEY,
    NAME VARCHAR2(10)
);

--3.
ALTER TABLE TB_CATEGORY ADD PRIMARY KEY(NAME);

--4.
ALTER TABLE TB_CLASS_TYPE MODIFY NAME NOT NULL;

--5.
ALTER TABLE TB_CLASS_TYPE MODIFY NO VARCHAR2(10)
                          MODIFY NAME VARCHAR2(20);
ALTER TABLE TB_CATEGORY MODIFY NAME VARCHAR2(20);

--6.
ALTER TABLE TB_CLASS_TYPE RENAME COLUMN NO TO CLASS_TYPE_NO;
ALTER TABLE TB_CLASS_TYPE RENAME COLUMN NAME TO CLASS_TYPE_NAME;
ALTER TABLE TB_CATEGORY RENAME COLUMN NAME TO CATEGORY_NAME;
                          
--7.
ALTER TABLE TB_CATEGORY RENAME COLUMN CATEGORY_NAME TO PK_CATEGORY_NAME;
ALTER TABLE TB_CLASS_TYPE RENAME COLUMN CLASS_TYPE_NO TO PK_CLASS_TYPE_NO;


--8.
INSERT INTO TB_CATEGORY VALUES ('공학','Y');
INSERT INTO TB_CATEGORY VALUES ('자연과학','Y');
INSERT INTO TB_CATEGORY VALUES ('의학','Y');
INSERT INTO TB_CATEGORY VALUES ('예체능','Y');
INSERT INTO TB_CATEGORY VALUES ('인문사회','Y');
COMMIT;

--9.
ALTER TABLE TB_DEPARTMENT ADD FOREIGN KEY(CATEGORY) REFERENCES TB_CATEGORY(PK_CATEGORY_NAME);

--10.
GRANT CREATE VIEW TO KH;
CREATE VIEW VW_학생일반정보
AS (SELECT STUDENT_NO,STUDENT_NAME,STUDENT_ADDRESS
    FROM TB_STUDENT);

--11.
CREATE VIEW VW_지도면담
AS (SELECT STUDENT_NAME,DEPARTMENT_NAME,PROFESSOR_NAME
    FROM TB_STUDENT
    JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
    JOIN TB_PROFESSOR ON (COACH_PROFESSOR_NO = PROFESSOR_NO));

--12.
CREATE VIEW VW_학과별학생수
AS (SELECT DEPARTMENT_NAME,COUNT(*)AS "STUDENT_COUNT"
    FROM TB_STUDENT
    JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
    GROUP BY DEPARTMENT_NAME);

--13.
UPDATE VW_학생일반정보
SET STUDENT_NAME = '송혁규'
WHERE STUDENT_NO = 'A213046';

--14.
--[WITH READ ONLY]

--15.
SELECT CLASS_NO AS "과목번호",CLASS_NAME AS "과목이름"
FROM TB_GRADE
LEFT JOIN TB_CLASS USING (CLASS_NO)
--GROUP BY '과목번호';