--1.
SELECT STUDENT_NO AS "학번",STUDENT_NAME AS "이름",ENTRANCE_DATE AS "입학년도"
FROM TB_STUDENT
WHERE DEPARTMENT_NO = (SELECT DEPARTMENT_NO
                       FROM TB_DEPARTMENT
                       WHERE DEPARTMENT_NAME = '영어영문학과')
ORDER BY ENTRANCE_DATE ASC;

--2.
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE LENGTH(PROFESSOR_NAME)!=3;

--3.
SELECT PROFESSOR_NAME AS "교수이름",TO_DATE(SUBSTR(PROFESSOR_SSN,1,6)) AS "나이"
FROM TB_PROFESSOR
WHERE SUBSTR(professor_ssn,8,1) IN ('1','3')
ORDER BY "나이" ;

--4.
SELECT SUBSTR(PROFESSOR_NAME,2) AS "이름"
FROM TB_PROFESSOR;

--5.
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE EXTRACT(YEAR FROM ENTRANCE_DATE)-EXTRACT(YEAR FROM TO_DATE(SUBSTR(STUDENT_SSN,1,6)))>=20;

--6.
SELECT TO_CHAR(TO_DATE(201225),'D')
FROM DUAL; --6이므로 금요일

--7.
SELECT EXTRACT(YEAR FROM TO_DATE('99/10/11','YY/MM/DD')),TO_DATE('49/10/11','YY/MM/DD')
FROM DUAL;

--8.
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE SUBSTR(STUDENT_NO,1,1)!='A';

--9.
SELECT ROUND(AVG(POINT),1)
FROM TB_GRADE
WHERE STUDENT_NO = 'A517178';

--10.
SELECT DEPARTMENT_NO AS "학과번호",COUNT(DEPARTMENT_NO) AS "학생수(명)"
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO;

--11.
SELECT COUNT(*)
FROM TB_STUDENT
WHERE COACH_PROFESSOR_NO IS NULL;

--12.
SELECT TO_NUMBER(SUBSTR(TERM_NO,1,4)) AS "년도",ROUND(AVG(POINT),1) AS "년도 별 평점"
FROM (SELECT *
    FROM TB_GRADE
    WHERE STUDENT_NO = 'A112113')
GROUP BY SUBSTR(TERM_NO,1,4)
ORDER BY TO_NUMBER(SUBSTR(TERM_NO,1,4));

--13.
SELECT DEPARTMENT_NO
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y'
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO;

--14.
SELECT STUDENT_NAME,COUNT(STUDENT_NAME)
FROM TB_STUDENT
GROUP BY STUDENT_NAME
HAVING COUNT(STUDENT_NAME)>=2;

--15.
SELECT SUBSTR(TERM_NO,1,4),SUBSTR(TERM_NO,5,2),POINT
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113';