--1
SELECT * FROM JOB;

--2
SELECT JOB_NAME FROM JOB;

--3
SELECT * FROM DEPARTMENT;

--4
SELECT EMP_NAME, EMAIL,PHONE,HIRE_DATE FROM EMPLOYEE;

--5
SELECT HIRE_DATE,EMP_NAME,SALARY FROM EMPLOYEE;

--6
SELECT EMP_NAME, SALARY*12 AS 연봉,(SALARY*(1+NVL(BONUS,0)))*12 AS 총수령액,((SALARY*(1+NVL(BONUS,0)))*12)-(SALARY*12*0.03) AS 실수령액
FROM EMPLOYEE;

--7
SELECT EMP_NAME,SALARY,HIRE_DATE,PHONE FROM EMPLOYEE WHERE SALARY BETWEEN (SELECT MIN_SAL FROM SAL_GRADE WHERE SAL_LEVEL='S1') AND (SELECT MAX_SAL FROM SAL_GRADE WHERE SAL_LEVEL='S1');

--8
SELECT EMP_NAME,SALARY,((SALARY*(1+NVL(BONUS,0)))*12)-(SALARY*12*0.03) AS "실수령액",HIRE_DATE FROM EMPLOYEE WHERE ((SALARY*(1+NVL(BONUS,0)))*12)-(SALARY*12*0.03)>=50000000;

--9
SELECT * FROM EMPLOYEE WHERE SALARY>=4000000 AND JOB_CODE='J2';

--10
SELECT EMP_NAME,DEPT_CODE, HIRE_DATE FROM EMPLOYEE WHERE DEPT_CODE IN ('D9','D5') AND HIRE_DATE<='02/01/01';

--11
SELECT * FROM EMPLOYEE WHERE HIRE_DATE BETWEEN '90/01/01' AND '01/01/01';

--12
SELECT EMP_NAME FROM EMPLOYEE WHERE EMP_NAME LIKE '%연';

--13
SELECT EMP_NAME,PHONE FROM EMPLOYEE WHERE NOT SUBSTR(PHONE,1,3)='010';

--14
SELECT * FROM EMPLOYEE WHERE (INSTR(EMAIL,'_')=5) AND (DEPT_CODE IN ('D9','D6')) AND (HIRE_DATE BETWEEN '90/01/01' AND '00/12/01') AND SALARY>=2700000;

--15
SELECT EMP_NAME,SUBSTR(EMP_NO,1,2) AS 생년,SUBSTR(EMP_NO,3,2) AS 생월,SUBSTR(EMP_NO,5,2) AS 생일 FROM EMPLOYEE;

--16
SELECT EMP_NAME,RPAD(SUBSTR(EMP_NO,1,7),14,'*') AS 주민번호 FROM EMPLOYEE;

--17
SELECT EMP_NAME , ABS(TRUNC(HIRE_DATE-SYSDATE)) AS 근무일수1,TRUNC(SYSDATE-HIRE_DATE) AS 근무일수2 FROM EMPLOYEE;

--18
SELECT * FROM EMPLOYEE WHERE MOD(EMP_ID,2)=1;

--19
SELECT * FROM EMPLOYEE WHERE TO_NUMBER(TO_CHAR(SYSDATE,'YYYY'))-TO_NUMBER(TO_CHAR(HIRE_DATE,'YYYY'))>=20;
SELECT * FROM EMPLOYEE WHERE MONTHS_BETWEEN(SYSDATE, HIRE_DATE) > 240;
--20
SELECT EMP_NAME, TO_CHAR(SALARY,'L9,999,999') FROM EMPLOYEE;

--21
SELECT EMP_NAME,DEPT_CODE,TO_CHAR(TO_DATE(SUBSTR(EMP_NO,1,6)),'YY"년" MM"월" DD"일"') AS 생일,TRUNC(TO_NUMBER(SYSDATE-TO_DATE(SUBSTR(EMP_NO,1,6)))/365) AS "나이(만)" FROM EMPLOYEE;

--22
SELECT EMP_ID,EMP_NAME ,(CASE WHEN DEPT_CODE = 'D5' THEN '총무부' WHEN DEPT_CODE = 'D6' THEN '기획부' WHEN DEPT_CODE = 'D9' THEN '영업부' END) AS 부서명 FROM EMPLOYEE WHERE DEPT_CODE IN ('D5','D6','D9') ORDER BY DEPT_CODE;

--23
SELECT EMP_NAME,SUBSTR(EMP_NO,1,6)AS 앞자리,SUBSTR(EMP_NO,8,14)AS 뒷자리,SUBSTR(EMP_NO,1,6)+SUBSTR(EMP_NO,8,14) AS 앞뒤합 FROM EMPLOYEE WHERE EMP_ID=201;

--24
SELECT SUM((SALARY*(1+NVL(BONUS,0)))*12) FROM EMPLOYEE WHERE DEPT_CODE = 'D5';

--25
SELECT COUNT (*) AS 전체직원수 ,COUNT(DECODE(EXTRACT(YEAR FROM HIRE_DATE),2001,1,NULL)) AS "2001년",COUNT(DECODE(EXTRACT(YEAR FROM HIRE_DATE),2002,1,NULL)) AS "2002년",COUNT(DECODE(EXTRACT(YEAR FROM HIRE_DATE),2003,1,NULL)) AS "2003년",COUNT(DECODE(EXTRACT(YEAR FROM HIRE_DATE),2004,1,NULL)) AS "2004년"
FROM EMPLOYEE;